// Balance timeline: runs the greedy bot on the real engine from a fresh save and prints the play
// time at which each plot gets built.
// Usage: node tools/balance.js [hours=24] [--json out.json] [--write-benchmark]
// --write-benchmark rewrites js/benchmark.js, which the TIMELINE panel in the game reads.
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const hours = Number(process.argv[2] || 24);
const jsonOut = process.argv.includes('--json') ? process.argv[process.argv.indexOf('--json') + 1] : null;
const ctx = { console, Math, Date, JSON, Object, Array, Set, Map, Number, String, isNaN, isFinite, Infinity, NaN, performance: { now: () => 0 }, localStorage: { getItem() { return null; }, setItem() {}, removeItem() {} } };
ctx.formatNum = (x) => String(x);
vm.createContext(ctx);
const load = (f) => vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'js', f), 'utf8'), ctx, { filename: f });
['ul-data.js', 'engine.js', 'plots.js', 'bot.js'].forEach(load);

const out = vm.runInContext(`(() => {
  const endMs = ${hours} * 3600 * 1000;
  const built = {};
  const events = [];
  const t0 = Date.now();
  let lastLog = 0;
  function check() {
    updateDecorationUnlocks();
    for (const p of PLOT_ORDER) {
      if (built[p.key] === undefined && plotIsBuilt(p)) { built[p.key] = BOT.state.gameMs; events.push({ key: p.key, name: p.name, ms: BOT.state.gameMs, P: gameState.currencies.P }); }
    }
    return false;
  }
  check();
  while (BOT.state.gameMs < endMs) {
    BOT.run(60000, check);
    if (BOT.state.gameMs - lastLog >= 3600000) { lastLog = BOT.state.gameMs; }
    if (Date.now() - t0 > 20 * 60 * 1000) break;
  }
  const lv = Object.values(gameState.levels).reduce((a, b) => a + b, 0);
  return { events, gameMs: BOT.state.gameMs, buys: BOT.state.buys, resets: BOT.state.resets, levels: lv, realMs: Date.now() - t0,
           currencies: Object.fromEntries(gameState.discoveredCurrencies.map(k => [k, gameState.currencies[k]])) };
})()`, ctx);

const fmt = (ms) => { const s = Math.round(ms / 1000); const h = Math.floor(s / 3600), m = Math.floor(s % 3600 / 60), ss = s % 60; return (h ? h + 'h ' : '') + (h || m ? m + 'm ' : '') + ss + 's'; };
for (const e of out.events) console.log(fmt(e.ms).padStart(12), '  ', e.key.padEnd(6), e.name);
console.log(`\nplayed ${fmt(out.gameMs)} in ${(out.realMs / 1000).toFixed(1)}s real, ${out.buys} buys, ${out.resets} resets, ${out.levels} levels`);
console.log(Object.entries(out.currencies).map(([k, v]) => `${k}=${Number(v).toExponential(2)}`).join('  '));
if (jsonOut) fs.writeFileSync(jsonOut, JSON.stringify(out, null, 1));

if (process.argv.includes('--write-benchmark')) {
  const plots = {};
  for (const e of out.events) plots[e.key] = e.ms;
  const last = out.events[out.events.length - 1];
  const note = `Greedy bot, fresh save, ${hours}h of play simulated. It built ${out.events.length} plots, the last one (${last.name}) at ${fmt(last.ms)}, then stalled. Plots after that are marked not reached: pace them with real play or MAX NEXT PLOT.`;
  const js = '// Generated by tools/balance.js --write-benchmark. Play time (ms) when the greedy bot built each plot.\n' +
    'const BOT_BENCHMARK = ' + JSON.stringify({ hours, plots, note }, null, 1) + ';\n';
  fs.writeFileSync(path.join(__dirname, '..', 'js', 'benchmark.js'), js);
  console.log('wrote js/benchmark.js');
}
