#!/usr/bin/env node
/* roblox/realm_luau.js: the realm contract as a Luau module for the Roblox client.
 *
 *   node roblox/realm_luau.js            write src/shared/Realm.luau from realm.json + edges.json
 *   node roblox/realm_luau.js --check    re-derive it and exit 1 when the committed file is stale
 *   options: --out <path>
 *
 * Reads art/realm.json (the camera, layers, biomes, sprites and particle fields of REALM.md) and art/edges.json (the
 * live node connections and the rift hotspot of DESIGN.md 3.8 / 3.11). The field names follow realm.json, so the
 * client's MapCamera.luau reads line for line against camera.js. What the client does not need (painter inputs,
 * keep-clear zones, tile plans, memory tables, prose) is left out; the tiles and atlas regions live in
 * src/shared/Assets.luau (generated by upload.js), so they have one source.
 *
 * `version` is the first 12 hex digits of sha256(realm.json + edges.json): a stale module is caught by --check.
 * The output is deterministic (fixed key order, numbers as JSON prints them).
 */
'use strict';
const fs = require('fs'), path = require('path'), crypto = require('crypto');

const ART = path.join(__dirname, '..');
const REPO = path.join(ART, '..');
const args = process.argv.slice(2);
const check = args.includes('--check');
const outArg = args.indexOf('--out');
const OUT = outArg >= 0 ? path.resolve(args[outArg + 1]) : path.join(REPO, 'src/shared/Realm.luau');
const LIMIT = 160 * 1024;

const realmText = fs.readFileSync(path.join(ART, 'realm.json'), 'utf8');
const edgesText = fs.readFileSync(path.join(ART, 'edges.json'), 'utf8');
const R = JSON.parse(realmText), E = JSON.parse(edgesText);
const version = crypto.createHash('sha256').update(realmText).update(edgesText).digest('hex').slice(0, 12);

// ------------------------------------------------------------------------------------------------ Luau literal writer
const IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;
const RESERVED = new Set(['and', 'break', 'do', 'else', 'elseif', 'end', 'false', 'for', 'function', 'if', 'in', 'local',
  'nil', 'not', 'or', 'repeat', 'return', 'then', 'true', 'until', 'while']);
function num(v) {
  if (!Number.isFinite(v)) throw new Error('not a finite number: ' + v);
  return JSON.stringify(v);
}
function key(k) { return IDENT.test(k) && !RESERVED.has(k) ? k : '[' + JSON.stringify(k) + ']'; }
/** One-line literal. `order` fixes the key order of objects (keys not listed follow, sorted). */
function lit(v) {
  if (v === null || v === undefined) return 'nil';
  if (typeof v === 'number') return num(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) return '{ ' + v.map(lit).join(', ') + ' }';
  const ks = Object.keys(v).filter(k => v[k] !== undefined && v[k] !== null);
  if (!ks.length) return '{}';
  return '{ ' + ks.map(k => key(k) + ' = ' + lit(v[k])).join(', ') + ' }';
}
const pick = (o, ks) => { const r = {}; for (const k of ks) if (o[k] !== undefined && o[k] !== null) r[k] = o[k]; return r; };

// ------------------------------------------------------------------------------------------------ the data
const cam = R.camera, dom = cam.viewportDomain;
const camera = {
  zMax: cam.zMax, zoomSlack: cam.zoomSlack, overscroll: cam.overscroll,
  domain: pick(dom, ['minW', 'minH', 'maxW', 'maxH', 'minAspect', 'maxAspect']),
  start: cam.start.center, introFactor: cam.start.introFromZoomFactor, introSeconds: cam.start.introSeconds,
};
const F = cam.feel;
const feel = {
  dragMouse: F.dragThreshold.mouse, dragTouch: F.dragThreshold.touch, velocityTau: F.velocitySmoothingTau,
  inertiaTau: F.inertiaTau, inertiaStop: F.inertiaStopSpeed, maxFling: F.maxFlingSpeed,
  rubberDistance: F.rubberBand.distance, rubberC: F.rubberBand.c, rubberReturn: F.rubberBand.returnSmoothTime,
  wheelFactor: F.wheel.factorPerNotch, wheelTau: F.wheel.smoothTau,
  pinchRubber: F.pinch.zoomRubber, pinchReturn: F.pinch.returnSmoothTime,
  doubleTapFactor: F.doubleTap.factor, doubleTapSeconds: F.doubleTap.seconds,
  flySmoothTime: F.flyTo.smoothTime, flyZoom: 0.9,
  padSpeed: F.gamepad.panSpeed, padDeadzone: F.gamepad.deadzone, padCurve: F.gamepad.curve, padZoomRate: F.gamepad.zoomRatePerSecond,
};
const bloomLayers = new Set(R.biomes.corrupt.bloom.layers.map(b => b.layer));
const layers = R.layers.map(L => {
  const o = { id: L.id, depth: L.depth, f: L.f, w: L.size[0], h: L.size[1], ax: L.anchor[0], ay: L.anchor[1],
    zHide: L.zHide || 0, zShow: L.zShow || 0, opaque: !!L.opaque, back: bloomLayers.has(L.id) };
  if (L.tint) o.tint = L.tint.rift;
  return o;
});
const B = R.biomes, C = B.corrupt;
const biome = {
  rift: { from: B.rift.from, to: B.rift.to },
  corrupt: { rect: C.rect, cover: C.cover, focus: C.focus, light: { radius: C.light.radius, falloff: C.light.falloff },
    bloom: C.bloom.layers.map(b => ({ layer: b.layer, size: b.size, color: b.color, alpha: b.alpha, at: b.local })) },
  wash: { realm: { color: B.wash.realm.color, alpha: B.wash.realm.alpha }, rift: { color: B.wash.rift.color, alpha: B.wash.rift.alpha } },
  vignette: { color: B.vignette.color, alpha: B.vignette.alpha },
};
const CH_KEYS = ['ch', 'type', 'amp', 'period', 'phase', 'speed', 'from', 'to', 'a', 'b', 'dur', 'ease', 'slot', 'seed', 'out'];
const INST_KEYS = ['x', 'y', 's', 'h', 'len', 't', 'a', 'r', 'c'];
const sprites = R.sprites.map(S => {
  const o = { name: S.name, layer: S.layer, regions: S.atlas, count: S.count, hangs: !!S.hangs,
    rmHide: /^hidden/.test(S.reducedMotion || ''), flicker: S.motion.some(m => m.type === 'flicker') };
  if (S.palette) o.palette = S.palette;
  if (S.color) o.color = S.color;
  o.instances = S.instances.map(i => {
    const r = pick(i, INST_KEYS);
    r.m = (i.m || []).map(m => pick(m, CH_KEYS));
    return r;
  });
  return o;
});
const P_KEYS = ['k', 'x', 'y', 'size', 'vx', 'vy', 'bx', 'by', 'bt', 'bp', 'a', 'ta', 'tt', 'tp', 'c', 'tau', 't', 'cg', 'low'];
const fields = R.fields.map(Fd => ({
  id: Fd.id, f: Fd.f, cell: Fd.cell, zHide: Fd.zHide || 0, zShow: Fd.zShow || 0, zFull: Fd.zFull,
  pool: Fd.poolMax, maxSize: Fd.maxSize, maxBob: Fd.maxBob,
  kinds: Fd.kinds.map(k => ({ name: k.name, regions: k.atlas, palette: k.palette, rift: k.rift, corrupt: k.corrupt })),
  particles: Fd.particles.map(p => { const r = pick(p, P_KEYS); r.low = p.low ? 1 : 0; return r; }),
}));

// ------------------------------------------------------------------------------------------------ the file
const L = [];
L.push('--!strict');
L.push('-- GENERATED by art/roblox/realm_luau.js from art/realm.json + art/edges.json. Do not edit by hand:');
L.push('--   cd art && node roblox/realm_luau.js          (--check fails when this file is stale)');
L.push('-- The realm contract of art/REALM.md for the client: camera constants and feel (2, 9.4); layers back to front');
L.push('-- (1; `back` = the layer has a Back container for a corrupt bloom, centred at bloom.at = realm.json `local`); biome');
L.push('-- weights and colours (5); ambient sprite groups with their resolved instances (6.1, 6.2; LOW uses the first');
L.push('-- count.LOW); particle fields (6.3; LOW uses low = 1); the node sockets (art keys: the game id cp is the socket cr);');
L.push('-- the live connections and the rift hotspot (art/edges.json; ids are game ids). Distances are world px or');
L.push('-- layer-local px, colours 0..255 RGB.');
L.push('');
L.push(`export type RGB = { number }
export type Channel = { ch: string, type: string, amp: number?, period: number?, phase: number?, speed: number?, from: number?,
	to: number?, a: number?, b: number?, dur: number?, ease: string?, slot: number?, seed: number?, out: string? }
export type Instance = { x: number, y: number, s: number, h: number?, len: number?, t: number?, a: number?, r: number?,
	c: number?, m: { Channel } }
export type SpriteColor = { realm: RGB, rift: RGB, corrupt: RGB }
export type SpriteGroup = { name: string, layer: string, regions: { string }, count: { HIGH: number, LOW: number },
	hangs: boolean, rmHide: boolean, flicker: boolean, palette: { RGB }?, color: SpriteColor?, instances: { Instance } }
export type Particle = { k: string, x: number, y: number, size: number, vx: number, vy: number, bx: number?, by: number?,
	bt: number?, bp: number?, a: number, ta: number?, tt: number?, tp: number?, c: number, tau: number, t: number?,
	cg: number, low: number }
export type FieldKind = { name: string, regions: { string }, palette: { RGB }, rift: RGB, corrupt: RGB }
export type Field = { id: string, f: number, cell: { number }, zHide: number, zShow: number, zFull: number,
	pool: { HIGH: number, LOW: number }, maxSize: number, maxBob: number, kinds: { FieldKind }, particles: { Particle } }
export type Layer = { id: string, depth: number, f: number, w: number, h: number, ax: number, ay: number, zHide: number,
	zShow: number, opaque: boolean, back: boolean, tint: RGB? }
export type Bloom = { layer: string, size: { number }, color: RGB, alpha: number, at: { number } }
export type Biome = {
	rift: { from: number, to: number },
	corrupt: { rect: { number }, cover: { number }, focus: { number }, light: { radius: { number }, falloff: { number } },
		bloom: { Bloom } },
	wash: { realm: { color: RGB, alpha: number }, rift: { color: RGB, alpha: number } },
	vignette: { color: RGB, alpha: number },
}
export type Domain = { minW: number, minH: number, maxW: number, maxH: number, minAspect: number, maxAspect: number }
export type Feel = { dragMouse: number, dragTouch: number, velocityTau: number, inertiaTau: number, inertiaStop: number,
	maxFling: number, rubberDistance: number, rubberC: number, rubberReturn: number, wheelFactor: number, wheelTau: number,
	pinchRubber: number, pinchReturn: number, doubleTapFactor: number, doubleTapSeconds: number, flySmoothTime: number,
	flyZoom: number, padSpeed: number, padDeadzone: number, padCurve: number, padZoomRate: number }
export type Edge = { from: string, to: string, p: { number } }
export type Realm = {
	version: string,
	world: { w: number, h: number },
	camera: { zMax: number, zoomSlack: number, overscroll: number, domain: Domain, start: { number }, introFactor: number,
		introSeconds: number },
	feel: Feel,
	layers: { Layer },
	zOrder: { string },
	biome: Biome,
	palette: { [string]: RGB },
	sprites: { SpriteGroup },
	fields: { Field },
	nodes: { [string]: { number } },
	alias: { [string]: string },
	edges: { Edge },
	rift: { cx: number, cy: number, rx: number, ry: number, fly: { number } },
}
`);
L.push('local Realm: Realm = {');
L.push(`\tversion = ${JSON.stringify(version)},`);
L.push(`\tworld = ${lit({ w: R.world.w, h: R.world.h })},`);
L.push(`\tcamera = ${lit(camera)},`);
L.push(`\tfeel = ${lit(feel)},`);
L.push('\tlayers = {');
for (const l of layers) L.push(`\t\t${lit(l)},`);
L.push('\t},');
L.push(`\tzOrder = ${lit(R.zOrder)},`);
L.push('\tbiome = {');
L.push(`\t\trift = ${lit(biome.rift)},`);
L.push(`\t\tcorrupt = ${lit(biome.corrupt)},`);
L.push(`\t\twash = ${lit(biome.wash)},`);
L.push(`\t\tvignette = ${lit(biome.vignette)},`);
L.push('\t},');
L.push(`\tpalette = ${lit(R.palette)},`);
L.push('\tsprites = {');
for (const s of sprites) {
  const head = Object.assign({}, s); delete head.instances;
  const h = lit(head);
  L.push(`\t\t${h.slice(0, -2)}, instances = {`);
  for (const i of s.instances) L.push(`\t\t\t${lit(i)},`);
  L.push('\t\t} },');
}
L.push('\t},');
L.push('\tfields = {');
for (const f of fields) {
  const head = Object.assign({}, f); delete head.particles;
  L.push(`\t\t${lit(head).slice(0, -2)}, particles = {`);
  for (const p of f.particles) L.push(`\t\t\t${lit(p)},`);
  L.push('\t\t} },');
}
L.push('\t},');
L.push(`\tnodes = ${lit(R.nodes)},`);
L.push(`\talias = ${lit({ cp: 'cr' })},`);
L.push('\tedges = {');
for (const e of E.edges) L.push(`\t\t${lit({ from: e.from, to: e.to, p: e.p })},`);
L.push('\t},');
L.push(`\trift = ${lit(E.rift)},`);
L.push('}');
L.push('');
L.push('return Realm');
const text = L.join('\n') + '\n';

// ------------------------------------------------------------------------------------------------ sanity
const nInst = sprites.reduce((a, s) => a + s.instances.length, 0), nPart = fields.reduce((a, f) => a + f.particles.length, 0);
if (E.edges.length !== 23) throw new Error(`edges.json: expected 23 edges, got ${E.edges.length}`);
for (const e of E.edges) if (e.p.length !== 8) throw new Error(`edge ${e.from}-${e.to}: 8 numbers expected`);
if (Buffer.byteLength(text) > LIMIT) { console.error(`Realm.luau is ${Buffer.byteLength(text)} bytes, over ${LIMIT}`); process.exit(1); }

if (check) {
  const old = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (old !== text) { console.error(`${path.relative(REPO, OUT)} is stale: run node roblox/realm_luau.js`); process.exit(1); }
  console.log(`${path.relative(REPO, OUT)} is up to date (version ${version})`);
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(REPO, OUT)}: ${(Buffer.byteLength(text) / 1024).toFixed(1)} KB, ${layers.length} layers, ` +
    `${sprites.length} sprite groups (${nInst} instances), ${fields.length} fields (${nPart} particles), ${E.edges.length} edges (version ${version})`);
}
