// Compares out/playtest.json with out/lua.json and writes roblox/tools/parity/REPORT.md.
// Numbers match within a relative tolerance of 1e-9 (|a - b| <= 1e-9 * max(1, |a|, |b|)); big values that left the
// double range on either side are compared as { sign, log10 } pairs (break_eternity / EternityNum mantissa + exponent),
// with the same tolerance on the log10. Booleans and strings must be equal.
//
// Every key belongs to a phase (phaseOf). Gate = every Phase 1 key in every Phase 1 scenario, plus the Phase 1 keys
// that only read state (tree nodes, egg cap, shop rows, playtime, can evolve, sparrow XP table) in every scenario.
// Phase 1 keys in later scenarios that multiply in a later system (fish, nest, quests, sacrifice, ...) are listed
// separately: they turn green as those phases land.
"use strict";
const fs = require("fs"), path = require("path");
const OUT = path.join(__dirname, "out");
const TOL = 1e-9;

const P1_UPGRADES = /^upgrade (p_value|p_speed|p_capacity|p_move_speed|pr_popcorn_mult|pr_radius_mult|pr_respawn_mult|s_more_popcorn|s_more_feathers|s_more_seeds|p_golden_popcorn_value|p_auric_silo|pr_golden_popcorn_mult) (level|max|effect|cost)$/;
function phaseOf(k) {
  if (P1_UPGRADES.test(k)) return "1";
  if (/^(egg cap|spawn interval|total multiplier|molt plumes|playtime mult|molt payout mult|pickup radius|can evolve)$/.test(k)) return "1";
  if (/^sparrow xp needed /.test(k)) return "1";
  if (/^tree (d_archivist_|d_unlock_archivist_tree)/.test(k)) return "7";
  if (/^tree /.test(k)) return "1";
  if (/^(p1|sim) /.test(k)) return "1";
  if (/^upgrade m_/.test(k)) return "4";
  if (/^fish mult /.test(k)) return "2";
  if (/^(aquarium|fish market|max fish buffs|market rep|contract offers)/.test(k)) return "2b";
  if (/^(nest|breed )/.test(k)) return "3";
  if (/^(riverside|sawmill)/.test(k)) return "3b";
  if (/^(mine |crow )/.test(k)) return "4";
  if (/^(desert|dave)/.test(k)) return "5";
  if (/^(parrot|exp |night )/.test(k)) return "6a";
  if (/^(artifact|proc |forge|infuse|fuse |aura |loot |inventory|sacrifice)/.test(k)) return "6b";
  if (/^(quest|mine entrance|totem|mythic)/.test(k)) return "6c";
  if (/^(echo|archivist)/.test(k)) return "7";
  return "?";
}
// Phase 1 keys that read only Phase 1 state, so they must match in every scenario
const STRUCTURAL = (k) => /^tree (?!d_archivist_|d_unlock_archivist_tree)/.test(k) || P1_UPGRADES.test(k) || /^(egg cap|playtime mult|can evolve)$/.test(k) || /^sparrow xp needed /.test(k);

function close(a, b) {
  if (typeof a === "number" && typeof b === "number") return Math.abs(a - b) <= TOL * Math.max(1, Math.abs(a), Math.abs(b));
  const isBig = (x) => x && typeof x === "object" && "L" in x;
  if (isBig(a) || isBig(b)) {
    const lg = (x) => (isBig(x) ? { s: x.s, L: x.L } : { s: Math.sign(x), L: Math.log10(Math.abs(x)) });
    const A = lg(a), B = lg(b);
    return A.s === B.s && Math.abs(A.L - B.L) <= TOL * Math.max(1, Math.abs(A.L), Math.abs(B.L));
  }
  return a === b;
}
const show = (v) => (v === undefined ? "(missing)" : typeof v === "object" && v !== null ? `1e${v.L.toFixed(6)}` : String(v));

function main() {
  const pt = JSON.parse(fs.readFileSync(path.join(OUT, "playtest.json"), "utf8"));
  const lu = JSON.parse(fs.readFileSync(path.join(OUT, "lua.json"), "utf8"));
  const luaBy = new Map(lu.results.map((r) => [r.name, r.values]));
  const gate = { total: 0, pass: 0, rows: [] };
  const blocked = { total: 0, pass: 0, rows: [] };
  const later = {}; // phase -> { total, produced, pass }
  const perScenario = [];
  for (const sc of pt.results) {
    const L = luaBy.get(sc.name) || {};
    let gT = 0, gP = 0;
    for (const [k, a] of Object.entries(sc.values)) {
      const ph = phaseOf(k), b = L[k], ok = b !== undefined && close(a, b);
      if (ph === "1" && (sc.p1 || STRUCTURAL(k))) {
        gate.total++; gT++;
        if (ok) { gate.pass++; gP++; } else gate.rows.push([sc.name, k, a, b]);
      } else if (ph === "1") {
        blocked.total++;
        if (ok) blocked.pass++; else blocked.rows.push([sc.name, k, a, b]);
      } else {
        const e = (later[ph] ||= { total: 0, produced: 0, pass: 0 });
        e.total++; if (b !== undefined) { e.produced++; if (ok) e.pass++; }
      }
    }
    perScenario.push([sc.name, sc.p1, gT, gP]);
  }
  const pct = (p, t) => (t ? ((100 * p) / t).toFixed(2) : "100.00");
  const lines = [];
  lines.push("# Peckwood parity report (Phase 1)", "");
  lines.push(`Playtest (\`playtest/js\`, headless, ${pt.generated.slice(0, 16)}Z) vs Peckwood's Luau (\`roblox/src\`, run in lune). Generated by \`node roblox/tools/parity/run.js\`.`, "");
  lines.push(`**Phase 1 gate: ${gate.pass} / ${gate.total} values match (${pct(gate.pass, gate.total)}%).** Tolerance: relative 1e-9 (big values on mantissa / log10).`, "");
  lines.push("The gate = every Phase 1 value in the Phase 1 scenarios (the playtest's 7 Phase 1 saves + the `p1 *` saves, each with a simulated run), plus the Phase 1 values that only read state (sunflower tree nodes, egg cap, shop rows, playtime, can evolve, sparrow XP table) in every one of the 69 scenarios.", "");
  lines.push(`Phase 1 values in later-phase scenarios that multiply in an unported system (fish, nest, quests, sacrifice, red panda, ...): ${blocked.pass} / ${blocked.total} match today; the rest wait for their phase (listed at the end).`, "");
  lines.push("## Later phases (not ported yet)", "", "| Phase | Values the playtest compares | Produced by Lua | Matching |", "|---|---|---|---|");
  for (const ph of Object.keys(later).sort()) lines.push(`| ${ph} | ${later[ph].total} | ${later[ph].produced} | ${later[ph].pass} |`);
  lines.push("", "## Phase 1 gate per scenario", "", "| Scenario | Phase 1 save | Gate values | Match |", "|---|---|---|---|");
  for (const [n, p1, t, p] of perScenario) lines.push(`| ${n} | ${p1 ? "yes" : ""} | ${t} | ${p} |`);
  lines.push("", "## Phase 1 gate mismatches", "");
  if (!gate.rows.length) lines.push("None.");
  else { lines.push("| Scenario | Value | Playtest | Lua |", "|---|---|---|---|"); for (const [n, k, a, b] of gate.rows.slice(0, 2000)) lines.push(`| ${n} | ${k} | ${show(a)} | ${show(b)} |`); }
  lines.push("", "## Phase 1 values blocked by later systems (informational)", "");
  if (!blocked.rows.length) lines.push("None.");
  else {
    const byKey = {};
    for (const [n, k] of blocked.rows) (byKey[k.replace(/^(sim|p1) .*/, "$1 ...")] ||= new Set()).add(n);
    lines.push("| Value | Scenarios |", "|---|---|");
    for (const [k, ns] of Object.entries(byKey)) lines.push(`| ${k} | ${[...ns].join(", ")} |`);
  }
  fs.writeFileSync(path.join(__dirname, "REPORT.md"), lines.join("\n") + "\n");
  return { gate, blocked, later };
}

module.exports = { main, phaseOf, close };
if (require.main === module) {
  const r = main();
  console.log(`Phase 1 gate: ${r.gate.pass}/${r.gate.total}; blocked-by-later: ${r.blocked.pass}/${r.blocked.total}`);
  for (const [n, k, a, b] of r.gate.rows.slice(0, 40)) console.log(` ${n} | ${k} | ${show(a)} | ${show(b)}`);
}
