// Writes roblox/src/shared/Birb/Data.luau from the playtest's live tables (numbers and structure only, no code):
// the 17 leveled upgrades (P / PR / S / M rows), every sunflower / desert / archivist node with its EFFECTIVE gates
// (playtest/js/data.js merged with archivist_data.js, exactly what PT.SUN holds at runtime), each node's parent list
// and all-parents rule (PT.sunParents / requiresAllSunflowerParents), and the 134 sunflower-field stations.
// Run: node roblox/tools/parity/gen_data.js   (run.js does it first, so the Luau data never drifts from the playtest)
"use strict";
const fs = require("fs"), path = require("path");
const { load, ROOT } = require("./headless.js");

function lua(v) {
  if (v === null || v === undefined) return "nil";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") {
    if (!Number.isFinite(v)) return v > 0 ? "math.huge" : "-math.huge";
    return String(v); // shortest round-trip form, which Luau parses to the same double
  }
  if (typeof v === "string") return JSON.stringify(v);
  if (Array.isArray(v)) return "{ " + v.map(lua).join(", ") + " }";
  const parts = [];
  for (const [k, x] of Object.entries(v)) if (x !== undefined && typeof x !== "function") parts.push((/^[A-Za-z_]\w*$/.test(k) ? k : `[${JSON.stringify(k)}]`) + " = " + lua(x));
  return "{ " + parts.join(", ") + " }";
}

function generate() {
  const { PT } = load();
  const UPS = [];
  for (const [id, d] of PT.UP) {
    if (!/^(p_|pr_|s_|m_)/.test(id)) continue; // the 17 rows of data.js; echo / nest rows belong to later phases
    UPS.push({ id, tree: d.tree, costCurrency: d.costCurrency, baseCost: d.baseCost, cost: d.cost, costMultiplier: d.costMultiplier, maxLevel: d.maxLevel,
      initialLevel: d.initialLevel, permanent: d.permanent, requires: d.requires && typeof d.requires === "object" ? d.requires : undefined, name: d.name, description: d.description });
  }
  const NEEDS_ALL = (id) => id === "d_unlock_archivist_tree" || id === "d_desert_auto_potion" || id.startsWith("d_archivist_echo_");
  const SUN = [];
  for (const [id, n] of PT.SUN) {
    SUN.push({ id, costCurrency: n.costCurrency, cost: n.cost, baseCost: n.baseCost, costMultiplier: n.costMultiplier, maxLevel: n.maxLevel || 1,
      requires: n.requires || undefined, parents: PT.sunParents(id), needsAll: NEEDS_ALL(id) || undefined, evolutionRequired: n.evolutionRequired,
      nestTierRequired: n.nestTierRequired, parrotRebirbRequired: n.parrotRebirbRequired, mineAreaRequired: n.mineAreaRequired, permanent: n.permanent || undefined,
      name: n.name, description: n.description });
  }
  // the archivist branch's own stations (Phase 7) are kept apart: the sunflower field holds the 134 base ones
  const STATIONS = PT.STATIONS.map((s) => ({ id: s[0], x: s[1], y: s[2], w: s[3], h: s[4] }));
  const ARCH_STATIONS = (PT.ARCHIVIST_STATIONS || []).map((s) => ({ id: s[0], x: s[1], y: s[2], w: s[3], h: s[4] }));
  const out = [
    "--!nolint",
    "-- GENERATED by roblox/tools/parity/gen_data.js from the playtest's runtime tables (playtest/js/data.js + archivist_data.js).",
    "-- Numbers and structure only. Do not edit by hand: rerun the generator (run.js does it on every parity run).",
    "local D = {}",
    "-- leveled upgrades (Birb upgradeManager rows): P / PR / S / M trees",
    "D.UP = {",
    ...UPS.map((u) => "\t" + lua(u) + ","),
    "}",
    "-- one-off and leveled tree nodes (Birb mk): parents = PT.sunParents(id), needsAll = every parent required",
    "D.SUN = {",
    ...SUN.map((u) => "\t" + lua(u) + ","),
    "}",
    "-- sunflower field stations in Birb's map order: id, x, y, w, h (px on map 1); __platform = the seed platform",
    "D.STATIONS = {",
    ...STATIONS.map((u) => "\t" + lua(u) + ","),
    "}",
    "D.ARCHIVIST_STATIONS = {",
    ...ARCH_STATIONS.map((u) => "\t" + lua(u) + ","),
    "}",
    "D.UP_BY_ID, D.SUN_BY_ID = {}, {}",
    "for i, u in D.UP do u.index = i; D.UP_BY_ID[u.id] = u end",
    "for i, n in D.SUN do n.index = i; D.SUN_BY_ID[n.id] = n end",
    "return D",
    "",
  ];
  const file = path.join(ROOT, "roblox/src/shared/Birb/Data.luau");
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, out.join("\n"));
  return { file, ups: UPS.length, sun: SUN.length, stations: STATIONS.length, arch: ARCH_STATIONS.length };
}

module.exports = { generate };
if (require.main === module) console.log(generate());
