#!/usr/bin/env node
/* gems/upload.js: upload the map node atlas (gems/out/node_atlas.png, from gems/atlas.py) to Roblox and write
 * src/shared/NodeAtlas.luau, which the client's node widgets read.
 *
 *   node gems/upload.js --dry-run          no network: write NodeAtlas.luau with the recorded id (or nil)
 *   node gems/upload.js                    upload if this sha256 is not recorded yet, then write NodeAtlas.luau
 *   options: --creator user:<id>|group:<id> (default ROBLOX_CREATOR, else the game owner user:5167569069)
 *
 * Same protocol and auth as roblox/upload.js (Open Cloud Assets API; the proxy adds the API key for apis.roblox.com):
 * POST /assets/v1/assets (assetType Image), then poll /assets/v1/operations/<id> for the asset id. The POST is sent
 * once; if its outcome is unknown the run stops and says so (find the image by its display name in the Creator
 * Dashboard and record it with --adopt <assetId>) rather than risk a duplicate.
 */
'use strict';
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const GEMS = __dirname, REPO = path.resolve(GEMS, '..', '..');
const PNG = path.join(GEMS, 'out', 'node_atlas.png'), META = path.join(GEMS, 'node_atlas.json');
const RECORD = path.join(GEMS, 'uploaded.json'), LUAU = path.join(REPO, 'src', 'shared', 'NodeAtlas.luau');
const API = 'https://apis.roblox.com/assets/v1';

const argv = process.argv.slice(2);
const arg = n => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : null; };
const dry = argv.includes('--dry-run');
const creator = arg('--creator') || process.env.ROBLOX_CREATOR || 'user:5167569069';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const headers = (extra = {}) => Object.assign(process.env.ROBLOX_API_KEY ? { 'x-api-key': process.env.ROBLOX_API_KEY } : {}, extra);

function record() { return fs.existsSync(RECORD) ? JSON.parse(fs.readFileSync(RECORD, 'utf8')) : { about: 'Roblox ids of the node atlas, keyed by the PNG sha256 (gems/upload.js).', assets: {} }; }

function writeLuau(id, meta) {
  const r = meta.rects, keys = Object.keys(r);
  const lines = keys.map(k => `\t\t${/^[a-z_]+$/.test(k) ? k : `["${k}"]`} = { ${r[k].join(', ')} },`);
  const src = `--!strict
-- GENERATED by art/gems/upload.js from art/gems/node_atlas.json + art/gems/uploaded.json. Do not edit by hand:
--   cd art && python3 gems/atlas.py && node gems/upload.js
-- The map node atlas (1024 px): the 21 layer gems, their locked copies and the energy ring parts (white: ring, glow,
-- comet, disc; tint them with ImageColor3). rects are { x, y, w, h } in atlas px; ringR is the ring radius / cell.
-- id = nil until the image is uploaded: the node widgets then keep their drawn discs.

export type NodeAtlas = { id: string?, size: number, cell: number, ringR: number, rects: { [string]: { number } } }

local NodeAtlas: NodeAtlas = {
\tid = ${id ? `"rbxassetid://${id}"` : 'nil'},
\tsize = ${meta.size},
\tcell = ${meta.cell},
\tringR = ${meta.ringR},
\trects = {
${lines.join('\n')}
\t},
}

return NodeAtlas
`;
  fs.writeFileSync(LUAU, src);
  console.log('wrote', path.relative(REPO, LUAU), id ? `(id ${id})` : '(no id)');
}

async function upload(sha) {
  const [kind, idStr] = creator.split(':');
  const req = { assetType: 'Image', displayName: 'Milestone Tree node atlas', description: `Map node gems and energy ring (sha256 ${sha.slice(0, 16)})`,
    creationContext: { creator: kind === 'group' ? { groupId: idStr } : { userId: idStr } } };
  const form = new FormData();
  form.append('request', JSON.stringify(req));
  form.append('fileContent', new Blob([fs.readFileSync(PNG)], { type: 'image/png' }), 'node_atlas.png');
  const res = await fetch(`${API}/assets`, { method: 'POST', headers: headers(), body: form });
  const text = await res.text();
  if (!res.ok) throw new Error(`create failed: HTTP ${res.status} ${text.slice(0, 400)}`);
  const op = JSON.parse(text);
  const opId = (op.path || '').split('/').pop() || op.operationId;
  console.log('operation', opId);
  for (let i = 0; i < 90; i++) {
    let o = op;
    if (!o.done) {
      await sleep(2000);
      const r = await fetch(`${API}/operations/${opId}`, { headers: headers() });
      if (!r.ok) { console.log('poll HTTP', r.status); continue; }
      o = await r.json();
    }
    if (o.done) {
      const id = o.response && o.response.assetId;
      if (!id) throw new Error('operation done without an asset id: ' + JSON.stringify(o).slice(0, 400));
      return { assetId: String(id), operationId: opId, moderation: o.response.moderationResult && o.response.moderationResult.moderationState };
    }
    op.done = false;
  }
  throw new Error(`operation ${opId} did not finish; run again later with --adopt <assetId> once it shows in the Creator Dashboard`);
}

// Node's fetch reaches the network through the session proxy only with NODE_USE_ENV_PROXY=1 (as roblox/upload.js)
if (!dry && (process.env.HTTPS_PROXY || process.env.https_proxy) && process.env.NODE_USE_ENV_PROXY !== '1') {
  const r = require('child_process').spawnSync(process.execPath, [__filename, ...argv], { stdio: 'inherit', env: { ...process.env, NODE_USE_ENV_PROXY: '1' } });
  process.exit(r.status == null ? 1 : r.status);
}
(async () => {
  const meta = JSON.parse(fs.readFileSync(META, 'utf8'));
  const sha = crypto.createHash('sha256').update(fs.readFileSync(PNG)).digest('hex');
  const rec = record();
  const adopt = arg('--adopt');
  if (adopt) rec.assets[sha] = { assetId: adopt, file: 'out/node_atlas.png', adopted: new Date().toISOString() };
  let hit = rec.assets[sha];
  if (!hit && !dry) {
    const up = await upload(sha);
    hit = rec.assets[sha] = Object.assign({ file: 'out/node_atlas.png', creator, uploadedAt: new Date().toISOString() }, up);
    console.log('uploaded', up.assetId, up.moderation || '');
  }
  fs.writeFileSync(RECORD, JSON.stringify(rec, null, 1) + '\n');
  writeLuau(hit && hit.assetId, meta);
})().catch(e => { console.error(e.message); process.exit(1); });
