// Pulls the Phase 7 data from Birb's live engine into playtest/js/archivist_data.js (numbers only, no code or art):
// the archivist sunflower nodes (d_unlock_archivist_tree + d_archivist_*), their station rectangles in the archivist
// tree view, the two Echo Field shop upgrades (p_echo_value, p_echo_capacity), and the live fields of every other sunflower node.
// Run from the repo root:  NODE_PATH=/opt/node-tools/node_modules node playtest/tools/build_archivist_data.js
const fs = require("fs"), path = require("path");
const { chromium } = require("playwright");
(async () => {
  const browser = await chromium.launch({ args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader"] });
  const p = await (await browser.newContext({ viewport: { width: 1600, height: 900 } })).newPage();
  await p.goto("https://birbplay.com/", { waitUntil: "domcontentloaded", timeout: 90000 });
  await p.waitForTimeout(6000);
  await p.click("#start-game-btn", { force: true });
  await p.waitForFunction(() => window.game && window.game.state, null, { timeout: 60000 });
  const data = await p.evaluate(async () => {
    const R = [...performance.getEntriesByType("resource")].map((r) => r.name);
    const ed = await import(R.find((n) => /\/editors-[^/]+\.js$/.test(n)));
    const plain = (u) => Object.fromEntries(Object.entries(u).filter(([k, v]) => typeof v !== "function" && k !== "name" && k !== "description" && k !== "icon"));
    const sunList = Object.values(ed).find((v) => Array.isArray(v) && v.some((u) => u && u.id === "d_unlock_archivist_tree" && "costCurrency" in u));
    const shopList = Object.values(ed).find((v) => Array.isArray(v) && v.some((u) => u && u.id === "p_echo_value"));
    const g = window.game; if (!g.sunflowerUpgradeStations.length) g.initSunflowerUpgradeStations();
    const isArch = (id) => id === "d_unlock_archivist_tree" || id.startsWith("d_archivist_");
    return {
      upgrades: sunList.filter((u) => isArch(u.id)).map(plain),
      stations: g.sunflowerUpgradeStations.filter((s) => isArch(s.id) && s.id !== "d_unlock_archivist_tree").map((s) => [s.id, s.x, s.y, s.width, s.height]),
      shop: shopList.filter((u) => /^p_echo_/.test(u.id)).map(plain),
      sunflower: sunList.filter((u) => !isArch(u.id)).map(plain), // every other node's live gates (evolution / nest / rebirb / max level), merged over data.js
    };
  });
  const out = path.resolve(__dirname, "../js/archivist_data.js");
  fs.writeFileSync(out, "// Generated by playtest/tools/build_archivist_data.js from Birb's live engine (numbers only).\nwindow.ARCHIVIST_DATA = " + JSON.stringify(data) + ";\n");
  console.log("wrote", out, data.upgrades.length, "nodes,", data.stations.length, "stations,", data.shop.length, "shop upgrades");
  await browser.close();
})().catch((e) => { console.error(e); process.exit(1); });
