"""Build playtest/js/data.js from birb-data (upgrades + tables) and the sunflower station layout.

Run from the repo root:  python3 playtest/tools/build_data.py
The page loads data.js as a plain script, so it works from file:// with no server.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BD = os.path.join(ROOT, "birb-data")
OUT = os.path.join(ROOT, "playtest", "js", "data.js")


def load(p):
    with open(p) as f:
        return json.load(f)


ups = load(os.path.join(BD, "upgrades.json"))
ups = ups if isinstance(ups, list) else ups["upgrades"]
stations = load(os.path.join(ROOT, "playtest", "tools", "sunflower_stations.json"))

tables = {}
for name in ["fish", "rods", "baits", "artifacts", "enemy_base_stats", "enemy_type_modifiers", "sacrifice_milestones", "quests"]:
    p = os.path.join(BD, "data", name + ".json")
    if os.path.exists(p):
        tables[name] = load(p)

with open(OUT, "w") as f:
    f.write("// GENERATED by playtest/tools/build_data.py from birb-data. Do not hand-edit.\n")
    f.write("window.BIRB_DATA = ")
    json.dump({"upgrades": ups, "stations": stations, "tables": tables}, f, separators=(",", ":"))
    f.write(";\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes,", len(ups), "upgrades,", len(stations), "stations")
