// Pulls the Expedition layout data from Birb's live engine into playtest/js/expedition_data.js:
// floor bounds, collision boxes, portals and fishing zones per floor, the hub portal, and the enemy base stats.
// Only numbers are copied (no art, no code). Run from the repo root:
//   NODE_PATH=/opt/node-tools/node_modules node playtest/tools/build_expedition_data.js
const fs = require("fs"), path = require("path");
const { chromium } = require("playwright");
(async () => {
  const browser = await chromium.launch({ args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader"] });
  const p = await (await browser.newContext({ viewport: { width: 1600, height: 900 } })).newPage();
  await p.goto("https://birbplay.com/", { waitUntil: "domcontentloaded", timeout: 90000 });
  await p.waitForTimeout(6000);
  await p.click("#start-game-btn", { force: true });
  await p.waitForFunction(() => window.game && window.game.expeditionManager, null, { timeout: 60000 });
  const data = await p.evaluate(async () => {
    const src = [...document.querySelectorAll("script[src],link[href]")].map((e) => e.src || e.href).find((u) => /\/assets\/maps-[^/]+\.js$/.test(u));
    const m = await import(src || "/assets/maps-CcKoUYtq.js");
    const em = game.expeditionManager, r1 = (v) => Math.round(v * 10) / 10;
    const portals = (id) => (m.b6[id] || []).filter((o) => o.type === "expedition_portal").map((o) => ({ type: em.normalizePortalType(o.portalType), x: o.x, y: o.y, r: em.getPortalRadiusFromObject(o) }));
    const floors = {};
    for (let f = 1; f <= 9; f++) {
      const id = em.getRunMapForFloor(f);
      floors[f] = { mapId: id, bounds: em.getRunBoundsForMapId(id), collisions: em.getCollisionRectsForMap(id).map((r) => [r.left, r.top, r.right, r.bottom].map(r1)),
        portals: portals(id), fishing: (m.b6[id] || []).filter((o) => o.type === "fishing_zone").map((o) => ({ x: o.x, y: o.y })) };
    }
    const base = {};
    for (const [k, v] of Object.entries(em.enemyBaseStats)) base[k] = { health: v.health, attack: v.attack, defense: v.defense, speed: v.speed, xpBase: v.xpBase, skillPointReward: v.skillPointReward };
    const hub = em.getHubMapId();
    const archivistCenter = em.getArchivistRitualCenter(em.getRunMapForFloor(9));
    return { floors, hub: { mapId: hub, portals: portals(hub), collisions: em.getCollisionRectsForMap(hub).map((r) => [r.left, r.top, r.right, r.bottom].map(r1)) }, enemyBaseStats: base, archivistCenter };
  });
  const out = path.resolve(__dirname, "../js/expedition_data.js");
  fs.writeFileSync(out, "// Generated by playtest/tools/build_expedition_data.js from Birb's live engine (numbers only).\nwindow.EXPEDITION_DATA = " + JSON.stringify(data) + ";\n");
  console.log("wrote", out, fs.statSync(out).size, "bytes");
  await browser.close();
})().catch((e) => { console.error(e); process.exit(1); });
