#!/usr/bin/env node
/* tools/camera_cases.js: parity cases for src/client/Map/MapCamera.luau, computed by art/camera.js itself.
 *
 *   node tools/camera_cases.js > data/unit/camera_cases.luau      (./test.sh unit does this)
 *
 * Each case is { f = <function>, i = { inputs... }, o = { expected outputs... } } with flat numbers; the Luau test
 * (tests/unit/map_camera.luau) calls the port with the same inputs and compares within 1e-9 relative. Sprite and
 * field cases refer to realm.json entries by index (Realm.luau keeps the same order). Deterministic (seeded).
 */
'use strict';
const path = require('path');
const ART = path.join(__dirname, '..', '..', 'art');
const RC = require(path.join(ART, 'camera.js'));
const R = require(path.join(ART, 'realm.json'));

const rnd = RC.rng(20260925);
const U = (a, b) => a + (b - a) * rnd();
const pickI = n => Math.floor(rnd() * n);
const cases = [];
const add = (f, i, o) => cases.push({ f, i, o });
const B = R.biomes;

// viewports inside and around the domain (map points), plus device sizes for mapScale
const views = [[1920, 1080], [2560, 1440], [1366, 768], [844, 390], [568, 1229], [760, 1080], [1024, 768], [667, 375]];
const V = () => { if (rnd() < 0.5) { const v = views[pickI(views.length)]; return { w: v[0], h: v[1] }; }
  const h = U(320, 1440); return { w: Math.min(2560, Math.max(568, h * U(0.5, 3.4))), h }; };
const Cam = () => ({ x: U(-200, 4040), y: U(-200, 2760) });
const Z = v => U(RC.zMin(v) * 0.9, 1.35);

for (let k = 0; k < 30; k++) {
  const d = { w: Math.round(U(300, 5200)), h: Math.round(U(200, 2400)) };
  const m = RC.mapScale(d);
  add('mapScale', [d.w, d.h], [m.scale, m.w, m.h, m.box.w, m.box.h]);
}
for (let k = 0; k < 60; k++) {
  const L = R.layers[pickI(R.layers.length)], v = V(), C = Cam(), z = Z(v);
  const Ld = { f: L.f, w: L.size[0], h: L.size[1], ax: L.anchor[0], ay: L.anchor[1] };
  const o = RC.layerOffset(Ld, C, z, v);
  add('layerOffset', [Ld.f, Ld.w, Ld.h, Ld.ax, Ld.ay, C.x, C.y, z, v.w, v.h], [o.x, o.y, o.scale]);
}
for (let k = 0; k < 30; k++) {
  const v = V(), C = Cam(), z = Z(v), z2 = Z(v), S = { x: U(0, v.w), y: U(0, v.h) };
  const o = RC.zoomAt(C, z, z2, S, v);
  add('zoomAt', [C.x, C.y, z, z2, S.x, S.y, v.w, v.h], [o.x, o.y]);
}
for (let k = 0; k < 60; k++) {
  const v = V(), C = Cam(), z = U(0.1, 1.5), rubber = k % 2 === 1;
  const o = RC.clampCamera(C, z, v, { rubber });
  add('clampCamera', [C.x, C.y, z, v.w, v.h, rubber ? 1 : 0], [o.x, o.y, o.z]);
}
for (let k = 0; k < 10; k++) { const x = U(0, 400); add('rubberBand', [x], [RC.rubberBand(x)]); }
for (let k = 0; k < 30; k++) {
  const v = V(), z = Z(v), C = k < 10 ? { x: U(2200, 3840), y: U(900, 1600) } : Cam();
  const w = RC.biome(C, B, z, v);
  add('biome', [C.x, C.y, z, v.w, v.h], [w.rift, w.corrupt, w.cover]);
}
for (let k = 0; k < 20; k++) { const p = { x: U(2800, 3840), y: U(600, 1800) }; add('corruptLight', [p.x, p.y], [RC.corruptLight(B, p)]); }
for (let k = 0; k < 20; k++) {
  const Fi = pickI(R.fields.length), Fd = R.fields[Fi], kind = Fd.kinds[pickI(Fd.kinds.length)], Ki = Fd.kinds.indexOf(kind);
  const c = pickI(4), cg = U(0.1, 0.9), w = { rift: U(0, 1), corrupt: U(0, 1) }, p = { x: U(2800, 3840), y: U(700, 1700) };
  const col = RC.biomeFieldColor(kind, c, cg, w, B, p);
  add('biomeFieldColor', [Fi, Ki, c, cg, w.rift, w.corrupt, p.x, p.y], col);
}
const colored = R.sprites.map((S, i) => [S, i]).filter(([S]) => S.color);
for (let k = 0; k < 10; k++) {
  const [S, Si] = colored[pickI(colored.length)], w = { rift: U(0, 1), corrupt: U(0, 1) }, p = { x: U(2800, 3840), y: U(700, 1700) };
  add('biomeSpriteColor', [Si, w.rift, w.corrupt, p.x, p.y], RC.biomeSpriteColor(S.color, w, B, p));
}
for (let k = 0; k < 20; k++) { const a = Math.floor(U(0, 1e6)), b = Math.floor(U(0, 5000)); add('hash01', [a, b], [RC.hash01(a, b)]); }
for (let k = 0; k < 80; k++) {
  const Si = k < 16 ? k : pickI(R.sprites.length), S = R.sprites[Si], Ii = pickI(S.instances.length), t = U(0, 900);
  const s = RC.spriteState(S.instances[Ii], t);
  add('spriteState', [Si, Ii, t], [s.dx, s.dy, s.rot, s.scale, s.alpha, s.grad]);
}
for (let k = 0; k < 9; k++) {
  const Fi = k % 3, Fd = R.fields[Fi], low = k >= 6, v = V(), C = Cam(), z = U(0.5, 1.3), t = U(0, 600);
  const cc = RC.clampCamera(C, z, v);
  const field = Object.assign({}, Fd, { cell: { w: Fd.cell[0], h: Fd.cell[1] }, particles: low ? Fd.particles.filter(p => p.low === 1) : Fd.particles });
  const out = [];
  for (const p of RC.fieldPlace(field, cc, cc.z, v, t)) out.push(p.i + 1, p.x, p.y, p.size, p.alpha);
  add('fieldPlace', [Fi, low ? 1 : 0, cc.x, cc.y, cc.z, v.w, v.h, t], out);
}

const num = x => { if (!Number.isFinite(x)) throw new Error('bad number ' + x); return JSON.stringify(x); };
const lines = ['-- GENERATED by port/tools/camera_cases.js from art/camera.js + art/realm.json. Do not edit.', 'return {'];
for (const c of cases) lines.push(`\t{ f = "${c.f}", i = { ${c.i.map(num).join(', ')} }, o = { ${c.o.map(num).join(', ')} } },`);
lines.push('}');
process.stdout.write(lines.join('\n') + '\n');
