# Writes src/shared/ZoneMaps.luau from the web build's ZONE_SVG (the exploration zones' backgrounds) as lines.
# usage: python3 zonemaps.py <milestone-tree-ng.html | zone_svg.js> <out.luau>
import re, base64, sys
s = open(sys.argv[1], encoding='utf-8').read()
m = re.findall(r'"([^"]+\.svg)":\s*"data:image/svg\+xml;base64,([^"]+)"', s)
out = ['--!nocheck',
       "-- The exploration zones' background drawings (zones/*.svg in the web game) as lines: { x1, y1, x2, y2, colour, width }.",
       '-- Generated by port/tools/zonemaps.py from the web build (ZONE_SVG).', 'return {']
for name, b in m:
    svg = base64.b64decode(b).decode()
    lines = []
    for tag, attrs in re.findall(r'<(line|rect)([^>]*)/?>', svg):
        a = dict(re.findall(r'([\w-]+)="([^"]*)"', attrs))
        col, w = a.get('stroke', '#ffffff').lstrip('#'), a.get('stroke-width', '1')
        if tag == 'line':
            lines.append((a.get('x1', '0'), a.get('y1', '0'), a.get('x2', '0'), a.get('y2', '0'), col, w))
        else:
            x, y, W, H = (float(a.get(k, '0')) for k in ('x', 'y', 'width', 'height'))
            for seg in ((x, y, x + W, y), (x + W, y, x + W, y + H), (x + W, y + H, x, y + H), (x, y + H, x, y)):
                lines.append(tuple('%g' % v for v in seg) + (col, w))
    out.append('\t["zones/%s"] = { %s },' % (name, ', '.join('{ %s, %s, %s, %s, "%s", %s }' % l for l in lines)))
out.append('}')
open(sys.argv[2], 'w').write('\n'.join(out) + '\n')
print(len(m), 'zones')
