// Runs the approved concept (rc-main/concepts/islands.html) headless and writes roblox/src/shared/IslandData.luau:
// per island the tile map, heights, palette, waterfalls and every prop as parts in tile units (exact concept geometry).
const fs = require('fs'), path = require('path');
const THREE = require('three');
const REPO = path.join(process.env.USERPROFILE, 'Downloads', 'rc-main');
const html = fs.readFileSync(path.join(REPO, 'concepts', 'islands.html'), 'utf8');
const src = html.slice(html.lastIndexOf('<script>') + 8, html.lastIndexOf('</script>'));
const el = () => ({ style: {}, classList: { add() {}, remove() {} }, addEventListener() {}, appendChild() {}, setAttribute() {}, set innerHTML(v) {}, set onclick(v) {}, dataset: {} });
class R { constructor() { this.shadowMap = {}; } setPixelRatio() {} setSize() {} render() {} }
const T2 = Object.assign({}, THREE, { WebGLRenderer: R, OrbitControls: class { constructor() { this.target = new THREE.Vector3(); } update() {} } });
const win = { THREE: T2, document: { getElementById: el, querySelectorAll: () => [], createElement: el }, matchMedia: () => ({ matches: false }),
  addEventListener() {}, innerWidth: 1400, innerHeight: 860, devicePixelRatio: 1, requestAnimationFrame() {} };
new Function(...Object.keys(win), 'window', src)(...Object.values(win), win);
const S = win.__s;
const r3 = v => Math.round(v * 1000) / 1000;
const hex = c => c.toString(16).padStart(6, '0');
const out = [];
out.push('--!nocheck\n-- GENERATED by scratch export.js from rc-main/concepts/islands.html (approved concept). Do not hand-edit.');
out.push('-- Per island: tile rows (0 void, 1 grass, 2 path, 3 water, 4 alt top), H rows (extra brick levels), palette,');
out.push('-- waterfalls, and props as parts in TILE units relative to the prop origin (ground level).');
out.push('-- part = { shape (0 box, 1 cylinder Y-axis), sx, sy, sz, px, py, pz, rx, ry, rz (XYZ euler rad), "rrggbb", mat, bob }');
out.push('-- mat: 0 plastic, 1 glass, 2 glow, 3 lamp (lit at night), 4 tank water');
out.push('return {');
const inv = new THREE.Matrix4(), m = new THREE.Matrix4(), p = new THREE.Vector3(), q = new THREE.Quaternion(), s = new THREE.Vector3(), e = new THREE.Euler();
S.scene.updateMatrixWorld(true);
S.D.forEach((d, k) => {
  if (k === 0) return; // the Park stays MapData + its own approved build
  const rows = d.T.map(r => r.join('')), hr = d.H.map(r => r.map(v => Math.min(9, v)).join(''));
  out.push(`\t${d.id} = { name = "${d.name}", gx = ${d.gx}, gz = ${d.gz}, W = ${d.W}, N = ${d.N},`);
  out.push(`\t\tgrass = { "${hex(d.grass[0])}", "${hex(d.grass[1])}" }, path = { "${hex(d.path[0])}", "${hex(d.path[1])}" }, alt = { "${hex((d.alt || d.grass)[0])}", "${hex((d.alt || d.grass)[1])}" },`);
  out.push(`\t\trows = { ${rows.map(r => '"' + r + '"').join(', ')} },`);
  out.push(`\t\tH = { ${hr.map(r => '"' + r + '"').join(', ')} },`);
  out.push(`\t\tspills = { ${S.spills.filter(x => x.isl === k).map(x => `{ ${x.li}, "${x.side}" }`).join(', ')} },`);
  out.push('\t\tprops = {');
  for (const g of S.props) {
    if (g.userData.isl !== k || !g.userData.kind) continue;
    let bob = null;
    inv.copy(g.matrixWorld).invert();
    const parts = [];
    g.traverse(o => {
      if (!o.isMesh) return;
      let a = o, b = 0;
      while (a && a !== g) { const hit = S.bobs.find(x => x[0] === a); if (hit) { b = 1; bob = [hit[1], hit[2]]; } a = a.parent; }
      m.multiplyMatrices(inv, o.matrixWorld); m.decompose(p, q, s); e.setFromQuaternion(q, 'XYZ');
      const geo = o.geometry.parameters; const cyl = o.geometry.type === 'CylinderGeometry';
      const sz = cyl ? [geo.radiusTop * 2 * s.x, geo.height * s.y, geo.radiusTop * 2 * s.z] : [s.x, s.y, s.z];
      const mt = o.material; const mat = mt === S.glass ? 1 : S.glowMats.includes(mt) ? 2 : S.lampMats.includes(mt) ? 3 : (mt.transparent ? 4 : 0);
      parts.push(`{ ${cyl ? 1 : 0}, ${sz.map(r3).join(', ')}, ${r3(p.x)}, ${r3(p.y)}, ${r3(p.z)}, ${r3(e.x)}, ${r3(e.y)}, ${r3(e.z)}, "${mt.color.getHexString()}", ${mat}, ${b} }`);
    });
    const u = g.userData;
    out.push(`\t\t\t{ "${u.kind}", ${r3(u.ti)}, ${r3(u.tj)}, ${r3(u.rot)}, ${bob ? `{ ${bob[0]}, ${bob[1]} }` : 'nil'}, {`);
    out.push('\t\t\t\t' + parts.join(',\n\t\t\t\t') + ' } },');
  }
  out.push('\t\t},\n\t},');
});
out.push('}');
const dst = path.join(REPO, 'roblox', 'src', 'shared', 'IslandData.luau');
fs.writeFileSync(dst, out.join('\n') + '\n');
console.log('wrote', dst, fs.statSync(dst).size, 'bytes; props', S.props.filter(g => g.userData.kind && g.userData.isl > 0).length);
